### ISSUE TITLE
mctpd  discuss

### ISSUE THREAD

**Issue by chenhongbo2022** [Intel-BMC/mctpd#1]
Compile **mctpd** miss dependency，this open source depends the third library **phosphor-dbus-interfaces**，such as：
1. #include <xyz/openbmc_project/MCTP/Base/server.hpp>
2. #include <xyz/openbmc_project/MCTP/SupportedMessageTypes/server.hpp>
But I did't find the corresponding file from **phosphor-dbus-interfaces**，Where can i get the dependent files？

Am i looking for the right one？Not uploaded to openbmc GitHub？

I want to integrate this to BMC. How should I integrate **mctpd** to bmc?

**Comment by jiaqingz-intel** [comment]
They are patches kept in Intel's internal phosphor-dbus-interface recipes. @arun-pm @sumbhat90 Can we opensource these patches?

**Comment by chenhongbo2022** [comment]
> They are patches kept in Intel's internal phosphor-dbus-interface recipes. @arun-pm @sumbhat90 Can we opensource these patches?

thank your answer，I think it can be open soure and we can discuss research together.

**Comment by chenhongbo2022** [comment]
I integrate **mctpd** into my bmc project with the **phosphor-dbus-interfaces** meet some compilation problems.

The compilation error is as follows：
/intel/mctpd-main/include/utils/types.hpp:4:10: fatal error: xyz/openbmc_project/MCTP/Base/server.hpp: No such file or directory
 #include <xyz/openbmc_project/MCTP/Base/server.hpp>

Have you encountered this problem in the integration process and how to solve it？

**Comment by sumbhat90** [comment]
https://github.com/Intel-BMC/openbmc/tree/intel/meta-openbmc-mods/meta-common/recipes-phosphor/dbus/phosphor-dbus-interfaces

Please apply the two MCTP related D-Bus interfaces patches on phosphor-dbus-interfaces (0028 and 0032), may be you are missing these patches in your meta layers.

**Comment by chenhongbo2022** [comment]
After patching, it can be compiled and passed. Thank u very much.

**Comment by chenhongbo2022** [comment]
In the absence of integrated **entity manager**, debugging mctp device discovery through configuration file **mctp_config.json**, who plays the role of bus owner？

As MCTP endpoint with pcie，the discovery command **Discovery Notify** returned a failure, the completion code:ERROR_UNSUPPORTED_CMD(0x05).

Suspect I need to start multiple instances.

**Comment by chenhongbo2022** [comment]
I tried to start multiple instances with pcie, such as a busowner and an endpoint, but failed.

What are the prerequisites for debugging using the PCIe configuration file?

**Comment by sumbhat90** [comment]
IntelBMC is designed to have MCTP endpoint on the BMC's PCIe interface. You can use external Bus Owner (ex: ME) to establish MCTP over PCIe communication.

**Comment by sumbhat90** [comment]
Hi @chenhongbo2022 , please check with our support channel [OpenBMC.Support@intel.com](mailto:OpenBMC.Support@intel.com) for such queries. Thanks!

**Comment by Kendidi** [comment]
@chenhongbo2022 Where are you running **mctpd** on? On host OS, or on BMC?  Thanks.

**Comment by chenhongbo2022** [comment]
> @chenhongbo2022 Where are you running **mctpd** on? On host OS, or on BMC? Thanks.

BMC.
